"""Initial_migration

Revision ID: 92ff6d98574c
Revises: 
Create Date: 2026-02-06 03:33:38.294630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ff6d98574c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Identifiant unique (ex: user.create)'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_slug'), 'permissions', ['slug'], unique=True)
    op.create_index(op.f('ix_permissions_uuid'), 'permissions', ['uuid'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=True)
    op.create_table('types_prise_charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_types_prise_charge'))
    )
    op.create_index(op.f('ix_types_prise_charge_code'), 'types_prise_charge', ['code'], unique=True)
    op.create_index(op.f('ix_types_prise_charge_id'), 'types_prise_charge', ['id'], unique=False)
    op.create_index(op.f('ix_types_prise_charge_uuid'), 'types_prise_charge', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_type'), 'users', ['type'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('administrateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_administrateurs_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrateurs'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_uuid'), 'audit_logs', ['uuid'], unique=True)
    op.create_table('medecins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=True, comment='Matricule professionnel'),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_medecins_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medecins')),
    sa.UniqueConstraint('matricule', name=op.f('uq_medecins_matricule'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_uuid'), 'refresh_tokens', ['uuid'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('secretaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desk_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_secretaires_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secretaires'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('visualiseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_access', sa.String(length=100), nullable=True, comment='Département accessible en lecture'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_visualiseurs_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visualiseurs'))
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('chef_service_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.ForeignKeyConstraint(['chef_service_id'], ['medecins.id'], name=op.f('fk_services_chef_service_id_medecins'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=True)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_uuid'), 'services', ['uuid'], unique=True)
    op.create_table('actes_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Code unique par service (ex: CS-GEN)'),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_actes_types_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actes_types')),
    sa.UniqueConstraint('code', 'service_id', name='uq_acte_type_code_service')
    )
    op.create_index(op.f('ix_actes_types_code'), 'actes_types', ['code'], unique=False)
    op.create_index(op.f('ix_actes_types_id'), 'actes_types', ['id'], unique=False)
    op.create_index(op.f('ix_actes_types_uuid'), 'actes_types', ['uuid'], unique=True)
    op.create_table('medecin_services',
    sa.Column('medecin_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], name=op.f('fk_medecin_services_medecin_id_medecins'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_medecin_services_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medecin_id', 'service_id', name=op.f('pk_medecin_services'))
    )
    op.create_table('actes_medicaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_patient', sa.String(length=100), nullable=False),
    sa.Column('prenom_patient', sa.String(length=100), nullable=False),
    sa.Column('numero_bc', sa.String(length=50), nullable=True, comment='Numéro Bon de Commande / Prise en charge'),
    sa.Column('date_acte', sa.DateTime(), nullable=False),
    sa.Column('cotation', sa.String(length=20), nullable=True, comment="Cotation de l'acte (ex: K20)"),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False, comment='Statut paiement: NON_PAYE, PAYE, GRATUIT'),
    sa.Column('acte_id', sa.Integer(), nullable=False),
    sa.Column('type_prise_charge_id', sa.Integer(), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.ForeignKeyConstraint(['acte_id'], ['actes_types.id'], name=op.f('fk_actes_medicaux_acte_id_actes_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_actes_medicaux_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], name=op.f('fk_actes_medicaux_medecin_id_medecins'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_prise_charge_id'], ['types_prise_charge.id'], name=op.f('fk_actes_medicaux_type_prise_charge_id_types_prise_charge'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actes_medicaux'))
    )
    op.create_index(op.f('ix_actes_medicaux_acte_id'), 'actes_medicaux', ['acte_id'], unique=False)
    op.create_index(op.f('ix_actes_medicaux_created_by_id'), 'actes_medicaux', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_actes_medicaux_date_acte'), 'actes_medicaux', ['date_acte'], unique=False)
    op.create_index(op.f('ix_actes_medicaux_id'), 'actes_medicaux', ['id'], unique=False)
    op.create_index(op.f('ix_actes_medicaux_medecin_id'), 'actes_medicaux', ['medecin_id'], unique=False)
    op.create_index(op.f('ix_actes_medicaux_nom_patient'), 'actes_medicaux', ['nom_patient'], unique=False)
    op.create_index(op.f('ix_actes_medicaux_numero_bc'), 'actes_medicaux', ['numero_bc'], unique=False)
    op.create_index(op.f('ix_actes_medicaux_prenom_patient'), 'actes_medicaux', ['prenom_patient'], unique=False)
    op.create_index(op.f('ix_actes_medicaux_statut'), 'actes_medicaux', ['statut'], unique=False)
    op.create_index(op.f('ix_actes_medicaux_uuid'), 'actes_medicaux', ['uuid'], unique=True)
    op.create_table('tarifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('acte_id', sa.Integer(), nullable=False),
    sa.Column('type_prise_charge_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False, comment='Montant en FCFA'),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de création'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Identifiant public unique (UUID)'),
    sa.ForeignKeyConstraint(['acte_id'], ['actes_types.id'], name=op.f('fk_tarifs_acte_id_actes_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_tarifs_service_id_services'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_prise_charge_id'], ['types_prise_charge.id'], name=op.f('fk_tarifs_type_prise_charge_id_types_prise_charge'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarifs')),
    sa.UniqueConstraint('service_id', 'acte_id', 'type_prise_charge_id', 'date_debut', name='uq_tarif_version')
    )
    op.create_index(op.f('ix_tarifs_acte_id'), 'tarifs', ['acte_id'], unique=False)
    op.create_index(op.f('ix_tarifs_date_debut'), 'tarifs', ['date_debut'], unique=False)
    op.create_index(op.f('ix_tarifs_id'), 'tarifs', ['id'], unique=False)
    op.create_index(op.f('ix_tarifs_service_id'), 'tarifs', ['service_id'], unique=False)
    op.create_index(op.f('ix_tarifs_type_prise_charge_id'), 'tarifs', ['type_prise_charge_id'], unique=False)
    op.create_index(op.f('ix_tarifs_uuid'), 'tarifs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarifs_uuid'), table_name='tarifs')
    op.drop_index(op.f('ix_tarifs_type_prise_charge_id'), table_name='tarifs')
    op.drop_index(op.f('ix_tarifs_service_id'), table_name='tarifs')
    op.drop_index(op.f('ix_tarifs_id'), table_name='tarifs')
    op.drop_index(op.f('ix_tarifs_date_debut'), table_name='tarifs')
    op.drop_index(op.f('ix_tarifs_acte_id'), table_name='tarifs')
    op.drop_table('tarifs')
    op.drop_index(op.f('ix_actes_medicaux_uuid'), table_name='actes_medicaux')
    op.drop_index(op.f('ix_actes_medicaux_statut'), table_name='actes_medicaux')
    op.drop_index(op.f('ix_actes_medicaux_prenom_patient'), table_name='actes_medicaux')
    op.drop_index(op.f('ix_actes_medicaux_numero_bc'), table_name='actes_medicaux')
    op.drop_index(op.f('ix_actes_medicaux_nom_patient'), table_name='actes_medicaux')
    op.drop_index(op.f('ix_actes_medicaux_medecin_id'), table_name='actes_medicaux')
    op.drop_index(op.f('ix_actes_medicaux_id'), table_name='actes_medicaux')
    op.drop_index(op.f('ix_actes_medicaux_date_acte'), table_name='actes_medicaux')
    op.drop_index(op.f('ix_actes_medicaux_created_by_id'), table_name='actes_medicaux')
    op.drop_index(op.f('ix_actes_medicaux_acte_id'), table_name='actes_medicaux')
    op.drop_table('actes_medicaux')
    op.drop_table('medecin_services')
    op.drop_index(op.f('ix_actes_types_uuid'), table_name='actes_types')
    op.drop_index(op.f('ix_actes_types_id'), table_name='actes_types')
    op.drop_index(op.f('ix_actes_types_code'), table_name='actes_types')
    op.drop_table('actes_types')
    op.drop_index(op.f('ix_services_uuid'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_code'), table_name='services')
    op.drop_table('services')
    op.drop_table('visualiseurs')
    op.drop_table('user_roles')
    op.drop_table('secretaires')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_uuid'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('medecins')
    op.drop_index(op.f('ix_audit_logs_uuid'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('administrateurs')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_type'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_types_prise_charge_uuid'), table_name='types_prise_charge')
    op.drop_index(op.f('ix_types_prise_charge_id'), table_name='types_prise_charge')
    op.drop_index(op.f('ix_types_prise_charge_code'), table_name='types_prise_charge')
    op.drop_table('types_prise_charge')
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_uuid'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_slug'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
